### ISSUE TITLE
The app doesn't build on macOS

### ISSUE THREAD

**Issue by nank1ro** [leoafarias/fvm#210]
**Describe the bug**
The current version of fvm doesn't build on macOS.

**To Reproduce**
1. Clone the repo
2. run `flutter run` on macOS

**Expected behavior**
The app should run on macOS

**Desktop (please complete the following information):**
 - OS: macOS 11.1 Big Sur (intel)
 - FVM Version 1.3.7 

**Additional context**
The file_chooser repo doesn't contains anymore a pubspec.yaml

**Comment by jans-y** [comment]
Meanwhile, until the new fixed version is released:
Just add ref of the commit to the file_chooser dependency inside `pubspec.yaml`
```
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 43901ebd12548a3c2a077d4dbeb3b56f0a0bdd09
```
