### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by JulianBissekkou** [leoafarias/fvm#339]
**Is your feature request related to a problem? Please describe.**
We are using fvm in our gitlab CI. We are using `leoafarias/fvm` from docker hub. The current version does not list the latest flutter release 2.2.3.

**Describe the solution you'd like**
It would be nice to have the latest fvm version in the docker image.

**Comment by marcellodesales** [comment]
@JulianBissekkou can you point me to your `.gitlab-ci.yml`?

**Comment by JulianBissekkou** [comment]
The project is not open source. So here are the parts that i can share:

Here my .gitlab.yml
```
image: "leoafarias/fvm"

# Cache the flutter sdk, otherwise this will be installed again when a fvm command is called.
cache:
  paths:
    - .fvm/flutter_sdk

stages:
  - lint

before_script:
  - fvm install

lint_some_module:
  stage: lint
  script:
    - cd some_module
    - fvm flutter pub get
    - fvm flutter analyze
  only:
    - merge_requests
```

Here my fvm_config.json

```
{
  "flutterSdkVersion": "2.2.3"
}
```

When running `fvm install` it says an unknown release. For debug purposes I run `fvm releases` and 2.2.3 was not listed there.
